FROM almalinux:9
ENV Course="Devops with aws" \
    trainer="Sivakumar Reddy" \
    duration="120hrs"
ARG  ${username:-some-user}   
RUN echo "hello ${username}" > /tmp/devops.txt
CMD ["sleep","500"]    